# If a player is offline more than this number of hours at server start, his chunk loaders won't be loaded
MaxHoursOffline: 24

# Default amount of chunks for all players
DefaultChunksAmount:
  AlwaysOn: 0
  OnlineOnly: 9
  
# Max amount of chunks for each player
MaxChunksAmount:
  AlwaysOn: 9
  OnlineOnly: 41
  
# Chunk Loaders block types
OnlineOnlyBlockMaterial: IRON_BLOCK
OnlineOnlyBlockMetadata: 0
AlwaysOnBlockMaterial: DIAMOND_BLOCK
AlwaysOnBlockMetadata: 0
  
# Data Store to use, XML or MySQL, but extensions can add custom data stores
DataStore: XML

# Configuration for MySQL Data Store
MySQL:
  Hostname: localhost
  Username: BetterChunkLoader
  Password: BetterPassword
  Database: BetterChunkLoader
  